distributionBase=Joshua_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.Joshua.org/distributions/Joshua-7.6-bin.zip
zipStoreBase=Joshua_USER_HOME
zipStorePath=wrapper/dists
